{% set name = "pytspack" %}
{% set version = "0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/noaa-oar-arl/pytspack/{{ version }}.tar.gz
  sha256: 3e35e2c56ace4452dc3aadf030f081581da7257044cd66f24c3343f396cdca1e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('fortran') }}
    - python >=3.6
  host:
    - python
    - pip
  run:
    - python
    - numpy

about:
  home: https://github.com/noaa-oar-arl/{{ name }}
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: Python interface for Robert J. Renka's fortran TSPACK: Tension Spline Curve Fitting Package

extra:
  recipe-maintainers:
    - bbakernoaa
