{% set name = "pytspack" %}
{% set version = "0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/noaa-oar-arl/pytspack/archive/v{{ version }}.tar.gz
  sha256: 3e35e2c56ace4452dc3aadf030f081581da7257044cd66f24c3343f396cdca1e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pytspack

about:
  home: https://github.com/noaa-oar-arl/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface for Robert J. Renka's fortran TSPACK-Tension Spline Curve Fitting Package

extra:
  recipe-maintainers:
    - bbakernoaa
